version: '2'
services:
  ci:
    privileged: true
    build: ./
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
        - ./jenkins_files:/var/jenkins_home
        - ./docker_files:/var/lib/docker/
